version: '3.8'

services:
  thermoseer-web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=thermoseer
      - POSTGRES_PASSWORD=thermoseer
      - POSTGRES_DB=thermoseer_dev
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - cache:/usr/local/etc/redis

volumes:
  cache:
  postgres_data: