version: '3.1'

services:
  redis:
    container_name: redis-thermoseer
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - cache:/usr/local/etc/redis
    networks:
      - thermo

networks:
  thermo:
volumes:
  cache: