version: '3.1'

services:
  redis:
    container_name: redis-thermoseer
    image: redis
    ports:
      - "6375:6379"
    restart: unless-stopped
    volumes:
      - cache:/data
    networks:
      - thermo

networks:
  thermo:
volumes:
  cache: