# Generated by Django 4.0.5 on 2023-04-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scannertemperature',
            options={'ordering': ('-updated',)},
        ),
    ]
