# Generated by Django 4.0.5 on 2023-04-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scannertemperature',
            options={'ordering': ('-created',)},
        ),
    ]
