# Generated by Django 4.0.5 on 2023-04-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='message',
            name='error',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
