# Generated by Django 4.0.5 on 2023-04-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_temperature_scanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannertemperature',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
