# Generated by Django 4.0.5 on 2023-04-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_scannertemperature_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannertemperature',
            name='scanner_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
