# Generated by Django 4.0.5 on 2023-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_message_message_description_message_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
